export default defineAppConfig({
  lazyCodeLoading: "requiredComponents",
  pages: [
    "pages/splash/index",
    "pages/index/index",
    "pages/login/index",
    "pages/devices/index",
    "pages/messages/index",
    "pages/profile/index",
  ],
  subPackages: [
    { root: "pages/guide", pages: ["index"] },
    { root: "pages/collar-bind", pages: ["index"] },
    { root: "pages/wifi-config", pages: ["index"] },
    { root: "pages/wifi-result", pages: ["index"] },
    { root: "pages/pet-info", pages: ["index"] },
    { root: "pages/pet-avatar", pages: ["index"] },
    { root: "pages/avatar-progress", pages: ["index"] },
    { root: "pages/desktop-bind", pages: ["index"] },
    { root: "pages/desktop-pair", pages: ["index"] },
    { root: "pages/invite", pages: ["index"] },
    { root: "pages/settings", pages: ["index"] },
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "YEHEY",
    navigationBarTextStyle: "black",
    navigationStyle: "custom",
  },
  tabBar: {
    color: "#999999",
    selectedColor: "#333333",
    backgroundColor: "#ffffff",
    borderStyle: "white",
    list: [
      {
        pagePath: "pages/index/index",
        text: "主页",
        iconPath: "assets/tabbar/home.png",
        selectedIconPath: "assets/tabbar/home-active.png",
      },
      {
        pagePath: "pages/devices/index",
        text: "设备",
        iconPath: "assets/tabbar/devices.png",
        selectedIconPath: "assets/tabbar/devices-active.png",
      },
      {
        pagePath: "pages/messages/index",
        text: "消息",
        iconPath: "assets/tabbar/messages.png",
        selectedIconPath: "assets/tabbar/messages-active.png",
      },
      {
        pagePath: "pages/profile/index",
        text: "我的",
        iconPath: "assets/tabbar/profile.png",
        selectedIconPath: "assets/tabbar/profile-active.png",
      },
    ],
  },
});
