services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pet
      POSTGRES_PASSWORD: pet123
      POSTGRES_DB: pet_wechat
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
